DROP TABLE IF EXISTS TASKS;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
  ID SERIAL PRIMARY KEY NOT NULL,
  FULLNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
);

CREATE TABLE TASKS (
  ID INT PRIMARY KEY NOT NULL,
  -- ...
);

CREATE TABLE NOTIFICATIONS(
  ID INT PRIMARY KEY NOT NULL,
--  ....
);